name: Build and Run Kuzzle image
description: Build and Run Kuzzle image

inputs:
  KUZZLE_IMAGE:
    description: Kuzzle image target
    required: true

runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash

    - run: npm run build
      shell: bash

    - run: npm prune --omit=dev
      shell: bash

    - run: |
        export KUZZLE_IMAGE=${{ inputs.KUZZLE_IMAGE }}
        docker compose -f ./.ci/services.yml up -d
      shell: bash

    - run: |
        if [ "$ES_VERSION" == "7" ]; then
            YML_FILE='./.ci/services-7.yml'
        elif [ "$ES_VERSION" == "8" ]; then
            YML_FILE='./.ci/services-8.yml'
        else
            echo "Invalid ES_VERSION. It should be either '7' or '8'."
            exit 1 
        fi

        trap 'docker compose -f $YML_FILE logs' err

        export MAX_TRIES=60
        ./bin/wait-kuzzle

        trap - err
      shell: bash

    - run: docker compose -f ./.ci/services.yml down
      shell: bash
