name: kuzzleio/kuzzle-runner

on:
  push:
    branches:
      - master

env:
  DOCKER_PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"

jobs:
  publish-runner:
    name: kuzzle-runner Node.js
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/images/kuzzle-runner
          file: ./docker/images/kuzzle-runner/Dockerfile
          push: true
          build-args: NODE_LTS_VERSION=${{ matrix.node-version }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: kuzzleio/kuzzle-runner:${{ matrix.node-version }}